language: objective-c

before_install:
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean test --project SemverSwift.xcodeproj -scheme "SemverSwift" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
