language: objective-c
branches:
 only:
 - develop
xcode_project: SemverSwift.xcodeproj
xcode_scheme: SemverSwift
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2

script:
- xcodebuild clean build test -project SemverSwift.xcodeproj -scheme SemverSwift -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
