language: objective-c
branches:
 only:
 - develop
xcode_project: SemverSwift.xcodeproj
xcode_scheme: SemverSwift
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2

script:
- xcodebuild clean build test -project SemverSwift.xcodeproj -scheme SemverSwift -destination 'id=86B2CA7C-0247-4257-BFEA-8035084AF2CF'
